<script setup lang="ts">
import Card from 'lib/components/card/Card.vue';
import DocTitle from '../DocTitle.vue';
import Icon from 'lib/components/icon/Icon.vue';
import { WangsIcons } from 'lib/components/icon/Icon.vue.d';

const wangsIconsArray: WangsIcons[] = [
  'add',
  'arrow-down',
  'arrow-drop-down',
  'arrow-go-back',
  'arrow-up-s',
  'arrow-up-down',
  'arrow-left',
  'arrow-left-double',
  'arrow-left-right',
  'arrow-right',
  'arrow-right-double',
  'arrow-right-fill',
  'asset-view',
  'assignment',
  'audit',
  'barricade-line',
  'bell',
  'bell-alert',
  'borrow',
  'building',
  'building-4',
  'calendar',
  'calendar-todo',
  'chat-check',
  'change-tag',
  'check',
  'check-double-fill',
  'checkbox-circle',
  'checkbox-circle-fill',
  'checkbox-blank-circle',
  'close',
  'close-circle',
  'close-circle-fill',
  'coins',
  'completion',
  'dashboard',
  'delete-back',
  'delete-bin',
  'delete-bin-7',
  'device',
  'disposal',
  'download',
  'dropbox',
  'dragable-menu',
  'edit',
  'ellipsis-h',
  'emotion-happy-fill',
  'emotion-unhappy-fill',
  'error',
  'error-fill',
  'exchange',
  'extension-borrow',
  'eye',
  'eye-off',
  'flag',
  'file-copy',
  'file-copy-2-line',
  'file-edit',
  'file-history',
  'file-history-fill',
  'file-info',
  'files',
  'file-list-2',
  'file-list',
  'file-settings',
  'file-shield-2',
  'filter-fill',
  'filter',
  'folder',
  'group',
  'hand-coin',
  'handheld',
  'history',
  'image-add',
  'indeterminate-circle-fill',
  'info',
  'information-line',
  'link-unlink-m',
  'list-settings',
  'loader-4',
  'logout-box-r',
  'mail-open',
  'mail-send',
  'map-2',
  'map-pin',
  'menu',
  'menu-unfold',
  'more',
  'move-to',
  'node-tree',
  'note',
  'notification',
  'pair-tag',
  'pencil',
  'phone',
  'printer',
  'price-tag-3',
  'profile',
  'qr',
  'qr-scan',
  'refresh',
  'replace-tag',
  'report-tag',
  'repair-ticketing',
  'rfid',
  'round-keyboard-arrow-left',
  'round-keyboard-arrow-right',
  'round-keyboard-double-arrow-left',
  'round-keyboard-double-arrow-right',
  'search',
  'search-line',
  'search-eye',
  'settings',
  'shopping-cart-2',
  'smartphone',
  'sort-asc',
  'sort-desc',
  'spinner',
  'stack',
  'store',
  'subtract',
  'team',
  'time',
  'tools',
  'tracking',
  'unassign',
  'upload-2',
  'upload-cloud-2',
  'user',
  'user-add',
  'user-follow',
  'user-received-2-line',
  'user-search',
  'user-settings',
  'user-shared-2-line',
  'user-star',
  'user-unfollow',
  'verification',
  'pdf',
  'xls',
  'data',
  'doc',
];
</script>

<template>
  <Card>
    <template #header>
      <DocTitle name="Icon List" />
      <span>
        These icons were upscaled to 200% of their original size for better
        viewing.
      </span>
    </template>
    <template #content>
      <div class="flex flex-wrap gap-5 shrink-0">
        <div
          :key="icon"
          v-for="icon in wangsIconsArray"
          class="flex flex-col gap-1 justify-between items-center"
        >
          <Icon :icon="icon" class="scale-[200%]" />
          <span>{{ icon }}</span>
        </div>
      </div>
    </template>
  </Card>
</template>
